### ISSUE TITLE
fix(code): develop is red — gh#500's session-bar suites construct services without the telemetry gh#562 made required

### ISSUE THREAD

**Issue by adammarquette** [adammarquette/MarqSpec.Mcp.TopstepX#572]
**`develop` is red at `abd6ea0`.** `build & unit tests`, `integration tests` and `Analyze (csharp)` all fail; `coverage` and `image` are skipped behind them. Every open branch inherits this.

### Why

Two pull requests that were each green in isolation broke `develop` when both merged. Neither conflicts with the other textually, so nothing warned:

- **gh#562 (PR #564)** removed the optional `HostTelemetry?` parameter and its `?? new HostTelemetry()` fallback, making `telemetry` **required** on `BarCacheService`, `IndicatorCacheService`, `FootprintCacheService` and `IndicatorProjector`. It threaded the singleton through every construction site that existed on its base.
- **gh#500 (PR #567)** added session-bar test suites that construct those same services, written against the *old* optional signature.

Each merged cleanly. Together they do not compile:

```
error CS7036: There is no argument given that corresponds to the required parameter 'telemetry' of
'BarCacheService.BarCacheService(TopstepXDbContext, IMarketDataGateway, BarSessionCalendar,
IndicatorProjector, TimeProvider, ILogger<BarCacheService>, HostTelemetry)'
  [MarqSpec.Mcp.TopstepX.IntegrationTests.csproj]
  [MarqSpec.Mcp.TopstepX.Tests.csproj]
error CS7036: … 'IndicatorProjector.IndicatorProjector(TopstepXDbContext, IndicatorCatalog,
ILogger<IndicatorProjector>, HostTelemetry)' [MarqSpec.Mcp.TopstepX.Tests.csproj]
```

Known affected files, found while rebasing gh#505: `MarqSpec.Mcp.TopstepX.Tests/Tools/SessionBarToolBoundaryTests.cs` and `MarqSpec.Mcp.TopstepX.IntegrationTests/SessionBarToolServedReadTests.cs`. **Do not assume those are the only two** — build both test projects and fix every site the compiler names.

This is a semantic conflict, not a textual one: a required-parameter change is incompatible with any construction site added in parallel, and Git merges both happily. Worth a line in [`AGENT-MEMORY.md`](../documentation/AGENT-MEMORY.md) if nothing formal covers it — a signature tightening merged beside in-flight work will break `develop` even though both pull requests were green.

### Scope

Thread the telemetry singleton into every construction site the compiler names, using the pattern `develop` already uses in its sibling suites: a disposed fixture field, or `ConcurrencyHarness.Telemetry` where that fixture is already in scope. **Do not** reintroduce an optional parameter or a fallback — that would undo gh#562 and re-hide the class of gap it exists to expose.

Nothing else. This is a build fix, not a place to improve neighbouring code.

### Acceptance criteria

- [ ] `dotnet build MarqSpec.Mcp.TopstepX.slnx` succeeds with 0 errors, and both test projects run: unit and integration counts quoted.
- [ ] `git grep -nE "HostTelemetry" -- '*.cs'` shows no new optional parameter and no new fallback; any construction added is a disposed fixture field or a reuse of an existing one.
- [ ] `dotnet format --verify-no-changes` clean; `check-no-order-path.sh` green.
- [ ] CI green on the PR head, so `develop` goes green on merge.

### Traceability

gh#500, gh#562, PR #564, PR #567, PR #569.

Assisted-by: Claude Opus 5 (Claude Code)
